version: '3'
services:
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:0.9.0
    environment:
      - cluster.name=ESCluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opendistro-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.9.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.2
    environment:
      - XPACK_MONITORING_ENABLED=false
      - LOG_LEVEL=info
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.7.2
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs:/var/log/app
volumes:
  opendistro-1:
    driver: local